### ISSUE TITLE
IndexError in channel.response_time() function

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#125]
When we choose a single day logs with the following config.py
```python
DEBUGGER = True
LOG_DIRECTORY = "<valid-path>"
OUTPUT_DIRECTORY = "<valid-path>"
STARTING_DATE = "2013-1-1"
ENDING_DATE = "2013-1-1"
MINIMUM_NICK_LENGTH = 3

# change to ["ALL"] if want to perform analysis over all channels
CHANNEL_NAME = ["#kubuntu-devel"]
# CHANNEL_NAME = ["ALL"]

.... (rest of config same as config.py that exists in the code base)
```

We get the following error.
```shell
Working on: /home/systemlab03/TSRK/phd/IRCLogParser/parser_files/YearlyLogFiles/2013/01/01/#kubuntu-devel.txt
========> 30 on 16 nicks
['BluesKaj', 'Peace-', 'LordOfTime', 'TheLordOfTime', 'benonsoftware', 'Benny', 'Guest43293', 'rdieter_work', 'rdieter', 'jjesse-home_', 'jjesse-home', 'rdieter1', 'Mamarok', 'Mamarok_', 'G4MBY', 'PaulW2U']
========> 30 on 5000 nick_same_list
[['LordOfTime', 'TheLordOfTime'], ['benonsoftware', 'Benny', 'Guest43293'], ['rdieter_work', 'rdieter', 'rdieter1'], ['jjesse-home_', 'jjesse-home'], ['Mamarok', 'Mamarok_'], ['G4MBY', 'PaulW2U'], ['BluesKaj'], ['Peace-'], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
Traceback (most recent call last):
  File "sample.py", line 33, in <module>
    resp_time = channel.response_time(log_data, nicks, nick_same_list)
  File "/home/systemlab03/TSRK/phd/IRCLogParser/gitrepo/IRCLogParser/lib/analysis/channel.py", line 286, in response_time
    for i in range(graph_cumulative[len(graph_cumulative)-1] + 1):
IndexError: list index out of range
```

**Comment by prasadtalasila** [comment]
The problem disappears with ENDING_DATE = "2013-1-5" or ENDING_DATE = "2013-1-2".

I guess the function is expecting the ENDING_DATE to be greater than the STARTING_DATE. This is a wrong assumption to make.

**Comment by rohangoel96** [comment]
Yes! It was assumed that STARTING DATE > ENDING DATE. @kaushik-rohit and @kaushik-rohit can you just replace < and <= signs?
