### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/IRCLogParser#76]
The software fails to install when tried with `virtualenv`. I tried the single installation step outlined in the README.md page.
```shell
pip -v install -e .
```

The installation failed with the following log.
```shell
Obtaining file:///home/csis/test/vprof/IRCLogParser
  Running setup.py (path:/home/csis/test/vprof/IRCLogParser/setup.py) egg_info for package from file:///home/csis/test/vprof/IRCLogParser
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/csis/test/vprof/IRCLogParser/setup.py", line 4, in <module>
        import numpy
    ImportError: No module named numpy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/csis/test/vprof/IRCLogParser/setup.py", line 4, in <module>

    import numpy

ImportError: No module named numpy

----------------------------------------
Cleaning up...
  Removing temporary dir /home/csis/test/vprof/IRCLogParser/virt2/build...
Command python setup.py egg_info failed with error code 1 in /home/csis/test/vprof/IRCLogParser
Exception information:
Traceback (most recent call last):
  File "/home/csis/test/vprof/IRCLogParser/virt2/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/csis/test/vprof/IRCLogParser/virt2/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/csis/test/vprof/IRCLogParser/virt2/local/lib/python2.7/site-packages/pip/req.py", line 1145, in prepare_files
    req_to_install.run_egg_info()
  File "/home/csis/test/vprof/IRCLogParser/virt2/local/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/csis/test/vprof/IRCLogParser/virt2/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/csis/test/vprof/IRCLogParser

Storing debug log for failure in /home/csis/.pip/pip.log
```

The installation got off to a decent start once I put in the following steps from travis.yml file.
```shell
pip install -U pip wheel
pip install scipy
pip install numpy
pip -v install -e .
```
After installing a few packages, the installation again failed while installing `python-igraph` package. Please see the error log below.
```shell
Cleaning up...
  Removing source in /tmp/pip-build-M1Sh7a/pygraphviz
  Removing source in /tmp/pip-build-M1Sh7a/python-igraph
Command "/home/systemlab03/virt_env/virt1/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-M1Sh7a/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1KOqdX-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/systemlab03/virt_env/virt1/include/site/python2.7/pygraphviz" failed with error code 1 in /tmp/pip-build-M1Sh7a/pygraphviz/
Exception information:
Traceback (most recent call last):
  File "/home/systemlab03/virt_env/virt1/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/systemlab03/virt_env/virt1/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/systemlab03/virt_env/virt1/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/systemlab03/virt_env/virt1/local/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/systemlab03/virt_env/virt1/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/home/systemlab03/virt_env/virt1/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-M1Sh7a/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1KOqdX-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/systemlab03/virt_env/virt1/include/site/python2.7/pygraphviz" failed with error code 1 in /tmp/pip-build-M1Sh7a/pygraphviz/
```

**Comment by rohangoel96** [comment]
how about `python setup.py install` ?

**Comment by prasadtalasila** [comment]
Gives the following error.
```
...
Processing dependencies for IRCLogParser==1.0
Searching for t3SphinxThemeRtd
Reading https://pypi.python.org/simple/t3SphinxThemeRtd/
No local packages or working download links found for t3SphinxThemeRtd
error: Could not find suitable distribution for Requirement.parse('t3SphinxThemeRtd')
```

**Comment by kaushik-rohit** [comment]
Fixed. Can you please try again with pip -v install -e . and confirm.

**Comment by prasadtalasila** [comment]
I tried the latest commit on the development branch (74c88f0) inside a virtualenv environment. It gives the following error.

```
Command "/home/user/virtenv/myproject/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-P7zgfa/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-VwZXBz-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/virtenv/myproject/include/site/python2.7/pygraphviz" failed with error code 1 in /tmp/pip-build-P7zgfa/pygraphviz/
Exception information:
Traceback (most recent call last):
  File "/home/user/virtenv/myproject/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/user/virtenv/myproject/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/user/virtenv/myproject/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/user/virtenv/myproject/local/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/user/virtenv/myproject/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/home/user/virtenv/myproject/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-P7zgfa/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-VwZXBz-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/virtenv/myproject/include/site/python2.7/pygraphviz" failed with error code 1 in /tmp/pip-build-P7zgfa/pygraphviz/
```

**Comment by kaushik-rohit** [comment]
@prasadtalasila my PR hasn't been merged yet. it is fixed in that.

**Comment by rohangoel96** [comment]
@kaushik-rohit merged https://github.com/prasadtalasila/IRCLogParser/pull/82. Close necessary issues if it's installing correctly now.

**Comment by kaushik-rohit** [comment]
@prasadtalasila Sir, can you confirm it is working for you? I have checked it on my machine and also the travis build is working properly. The PR has been committed to dev branch.

**Comment by prasadtalasila** [comment]
The install is primarily failing because of missing OS level dependencies. Most of the dependencies specified in setup.py are python bindings to underlying third-party packages. In order for the software to work, these OS level packages must be installed too. I made a list of few required one in [vagrant script](https://github.com/prasadtalasila/IRCLogParser/blob/06ce26050d8a75c1efb493f82e0fc04ae19e9114/script/vagrant.sh). Do identify all of them and put in the install script that has to be run before the pip command.

**Comment by prasadtalasila** [comment]
We need to have the install script in place before we can close this issue.
